### ISSUE TITLE
Remove members that "do not agree" to terms_conditions

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-shortcode#23]
Currently the terms_conditions is not being loaded since version 1.1 came out. 
members that "do not agree" to terms_conditions should not be loaded into Artsdata and not appear in the member directory.

Email from Frédéric 14-Jun-2023
```
Hi Gregory,

Could you please confirm that the field "terms_conditions_v1_0" is also used to determine which records are loaded to Artsdata? This is our consent question. Any member who does not agree should not be loaded to Artsdata.

I scanned the pilot project doc about this and I couldn't find anything indicating clearly that this field was taken into account prior to loading the data.

Frédéric
```

**Comment by saumier** [comment]
Data currently available from Wordpress API

empty
agree (v1.1)
agree (v1.0)
agree and disclose (v1.1)
do not agree (v1.1)
agree and disclose (v1.0)
do not agree (v1.0)

**Comment by saumier** [comment]
Of the above members, there are 3 with "do not agree (v1.0)" and 1 with "do not agree (v1.1)"

**Comment by fjjulien** [comment]
After discussing this issue with the team, we all agreed that consent should be required for member data to be loaded to Artsdata and displayed in the directory. No consent = no listing in the directory.

On the CAPACOA side of things, we have a lot of work to make this requirement clear across all our membership forms and resources. In addition, we have several members who have simply been paying their membership invoice without even bothering to log into their account. The good news is: the consent requirement will be a good incentive.

@saumier Could you give me the names of the members who haven't given consent?

**Comment by saumier** [comment]
@fjjulien Here is the SPARQL to get the consent status of all members.

There are many with "empty", and there are 4 with "do not agree".

You can search the results for "do not agree".

https://s.zazuko.com/NMkm7K

**Comment by fjjulien** [comment]
We also need a system to remove terminated members from the directory. I'll open another issue about this.

**Comment by dugost** [comment]
@fjjulien Staging checkout has updated EN/FR wording for "No thanks". Will reflect this on production site.

**Comment by fjjulien** [comment]
> Currently the terms_conditions is not being loaded since version 1.1 came out.

I believe this was fixed in version 2.0 of [capacoa-artsdata-usermeta](https://github.com/culturecreates/capacoa-artsdata-usermeta/tree/main). I see the field in the list of extracted fields.

**Comment by fjjulien** [comment]
> members that "do not agree" to terms_conditions should not be loaded into Artsdata and not appear in the member directory.

@saumier Logically and Ethically, that is how we should proceed. However, if this presents any technical challenges, I am not adamant that we should proceed in this fashion. Here's why:

-  There is value in being able to consult all consent data in Artsdata (rather than having to export the membership database to .csv). Dessa or myself can use your [sparql query](https://s.zazuko.com/NMkm7K) to quickly check member consents and identify which ones should be contacted to check in on their consent status.
- For organizations, we are extracting and loading only publicly-available information (except perhaps the Business Number). There is absolutely no danger in having this information available in Artsdata.
- There is no logical reason why a member would not give consent. If we contact them and speak them through it, 100% should give their consent.

All in all, it's probably not worth it setting up an exclusion mechanism at the ETL level if it presents any complexity. If it's easy to code, proceed. If it is going to take more than 15-20 mins, leave it.

This being said, if we do not create an exclusion mechanism at the ETL level, we should still create one at the display level.

I will let you assess with of the two exclusion mechanisms is easiest to code.

**Comment by fjjulien** [comment]
For priority setting purposes, this issue is not in direct scope for the current iteration. #18 and #25 are higher priority.

**Comment by saumier** [comment]
@fjjulien There are currently 2 members that are "do not agree" to terms_conditions

```
https://capacoa.ca/member/125
https://capacoa.ca/vocabulary#TermsConditions_do%20not%20agree%20%28v1.1%29
Palais Montcalm - Maison de la musique
https://www.palaismontcalm.ca/
```
```
https://capacoa.ca/member/274
https://capacoa.ca/vocabulary#TermsConditions_do%20not%20agree%20%28v1.1%29
Centre culturel Desjardins
https://www.spectaclesjoliette.com/
```

I have removed all members that chose TermsConditions_do_not_agree_(v1.1) from the CAPACOA directory.  But they are still being uploaded to the CAPACA graph in Artsdata.  It may take a day or 2 for the webpage cache to refresh.
